- name: Create k8s.conf for sysctl
  template:
    src: modules.k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Create sysctl.d k8s.conf file
  template:
    src: sysctl.k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Apply sysctl settings

- name: Enable IP forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward=1'
    backup: yes
  notify: Apply sysctl settings

- name: Save iptables rules to a shell script
  ansible.builtin.copy:
    dest: /usr/local/bin/apply-iptables-rules.sh
    content: |
      #!/bin/bash
      # Apply NAT masquerading on wlan0 interface
      /sbin/iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
      # Allow forwarding of established connections from wlan0 to eth0
      /sbin/iptables -A FORWARD -i wlan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
      # Allow forwarding of all connections from eth0 to wlan0
      /sbin/iptables -A FORWARD -i eth0 -o wlan0 -j ACCEPT
      # Allow incoming TCP traffic on port 9879 - k8s cilium hubble
      /sbin/iptables -A INPUT -p tcp --dport 9879 -j ACCEPT
    mode: '0755'

- name: Create systemd service for iptables-restore
  ansible.builtin.copy:
    dest: /etc/systemd/system/iptables-apply.service
    content: |
      [Unit]
      Description=Set iptables rules on startup for wlan0 and eth0 forwarding

      [Service]
      ExecStart=/usr/local/bin/apply-iptables-rules.sh
      Type=oneshot
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Enable and start iptables-restore service
  ansible.builtin.systemd:
    name: iptables-apply
    enabled: yes
    state: restarted
    daemon_reload: yes