---
- name: Install and configure isc-dhcp-server and update iptables
  hosts: localhost
  become: true
  tasks:
    - name: Install 50-cloud-init.yaml
      template:
        src: 50-cloud-init.yaml.j2
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        group: root
        mode: '0644'
      vars:
        wifi_bearden_password: "{{bearden_wifi_pass}}"
      notify:
      - Apply Netplan

    - name: Reboot the system
      command: reboot
      async: 0
      poll: 0
      become: true
      ignore_errors: true
  handlers:
    - name: Apply Netplan
      command: netplan apply
